-- v2.0.3: Horoscope readings table
-- Stores the narrative interpretation generated by the interpretation engine.
-- The reading column is JSONB containing: overall_outlook, dominant_theme,
-- key_transits, moon_guidance, mercury_warning, timing_window, confidence.

CREATE TABLE IF NOT EXISTS horoscope_readings (
    ticker         TEXT      NOT NULL,
    reading_date   DATE      NOT NULL,
    reading        JSONB     NOT NULL,
    dominant_theme TEXT      NOT NULL,
    confidence     DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, reading_date)
);

-- Index for filtering by theme across all tickers
CREATE INDEX IF NOT EXISTS idx_horoscope_theme ON horoscope_readings (dominant_theme);

-- Index for recent readings
CREATE INDEX IF NOT EXISTS idx_horoscope_date ON horoscope_readings (reading_date DESC);
